/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.app;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actual Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.riaps.app.ActualValue#getStringdefault <em>Stringdefault</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.ActualValue#getNumberdefault <em>Numberdefault</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.ActualValue#getBoolDefault <em>Bool Default</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.ActualValue#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see edu.vanderbilt.riaps.app.AppPackage#getActualValue()
 * @model
 * @generated
 */
public interface ActualValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Stringdefault</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stringdefault</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stringdefault</em>' containment reference.
   * @see #setStringdefault(StringDefault)
   * @see edu.vanderbilt.riaps.app.AppPackage#getActualValue_Stringdefault()
   * @model containment="true"
   * @generated
   */
  StringDefault getStringdefault();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.ActualValue#getStringdefault <em>Stringdefault</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stringdefault</em>' containment reference.
   * @see #getStringdefault()
   * @generated
   */
  void setStringdefault(StringDefault value);

  /**
   * Returns the value of the '<em><b>Numberdefault</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numberdefault</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numberdefault</em>' containment reference.
   * @see #setNumberdefault(NumberDefault)
   * @see edu.vanderbilt.riaps.app.AppPackage#getActualValue_Numberdefault()
   * @model containment="true"
   * @generated
   */
  NumberDefault getNumberdefault();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.ActualValue#getNumberdefault <em>Numberdefault</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Numberdefault</em>' containment reference.
   * @see #getNumberdefault()
   * @generated
   */
  void setNumberdefault(NumberDefault value);

  /**
   * Returns the value of the '<em><b>Bool Default</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool Default</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Default</em>' containment reference.
   * @see #setBoolDefault(BoolDefault)
   * @see edu.vanderbilt.riaps.app.AppPackage#getActualValue_BoolDefault()
   * @model containment="true"
   * @generated
   */
  BoolDefault getBoolDefault();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.ActualValue#getBoolDefault <em>Bool Default</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Default</em>' containment reference.
   * @see #getBoolDefault()
   * @generated
   */
  void setBoolDefault(BoolDefault value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' reference.
   * @see #setParam(ActorFormal)
   * @see edu.vanderbilt.riaps.app.AppPackage#getActualValue_Param()
   * @model
   * @generated
   */
  ActorFormal getParam();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.ActualValue#getParam <em>Param</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' reference.
   * @see #getParam()
   * @generated
   */
  void setParam(ActorFormal value);

} // ActualValue
