/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.app;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actual</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.riaps.app.Actual#getArgName <em>Arg Name</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.Actual#getArgValue <em>Arg Value</em>}</li>
 * </ul>
 *
 * @see edu.vanderbilt.riaps.app.AppPackage#getActual()
 * @model
 * @generated
 */
public interface Actual extends EObject
{
  /**
   * Returns the value of the '<em><b>Arg Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg Name</em>' reference.
   * @see #setArgName(ComponentFormal)
   * @see edu.vanderbilt.riaps.app.AppPackage#getActual_ArgName()
   * @model
   * @generated
   */
  ComponentFormal getArgName();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.Actual#getArgName <em>Arg Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg Name</em>' reference.
   * @see #getArgName()
   * @generated
   */
  void setArgName(ComponentFormal value);

  /**
   * Returns the value of the '<em><b>Arg Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg Value</em>' containment reference.
   * @see #setArgValue(ActualValue)
   * @see edu.vanderbilt.riaps.app.AppPackage#getActual_ArgValue()
   * @model containment="true"
   * @generated
   */
  ActualValue getArgValue();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.Actual#getArgValue <em>Arg Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg Value</em>' containment reference.
   * @see #getArgValue()
   * @generated
   */
  void setArgValue(ActualValue value);

} // Actual
