/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.app;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.riaps.app.InstanceSection#getInstances <em>Instances</em>}</li>
 * </ul>
 *
 * @see edu.vanderbilt.riaps.app.AppPackage#getInstanceSection()
 * @model
 * @generated
 */
public interface InstanceSection extends EObject
{
  /**
   * Returns the value of the '<em><b>Instances</b></em>' containment reference list.
   * The list contents are of type {@link edu.vanderbilt.riaps.app.Instance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instances</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instances</em>' containment reference list.
   * @see edu.vanderbilt.riaps.app.AppPackage#getInstanceSection_Instances()
   * @model containment="true"
   * @generated
   */
  EList<Instance> getInstances();

} // InstanceSection
