/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.app;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mdodel</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.vanderbilt.riaps.app.AppPackage#getMdodel()
 * @model
 * @generated
 */
public interface Mdodel extends EObject
{
} // Mdodel
