/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.app;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Req Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.riaps.app.ReqPort#getReq_type <em>Req type</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.ReqPort#getRep_type <em>Rep type</em>}</li>
 * </ul>
 *
 * @see edu.vanderbilt.riaps.app.AppPackage#getReqPort()
 * @model
 * @generated
 */
public interface ReqPort extends Port
{
  /**
   * Returns the value of the '<em><b>Req type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Req type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req type</em>' reference.
   * @see #setReq_type(Message)
   * @see edu.vanderbilt.riaps.app.AppPackage#getReqPort_Req_type()
   * @model
   * @generated
   */
  Message getReq_type();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.ReqPort#getReq_type <em>Req type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Req type</em>' reference.
   * @see #getReq_type()
   * @generated
   */
  void setReq_type(Message value);

  /**
   * Returns the value of the '<em><b>Rep type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rep type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rep type</em>' reference.
   * @see #setRep_type(Message)
   * @see edu.vanderbilt.riaps.app.AppPackage#getReqPort_Rep_type()
   * @model
   * @generated
   */
  Message getRep_type();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.ReqPort#getRep_type <em>Rep type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rep type</em>' reference.
   * @see #getRep_type()
   * @generated
   */
  void setRep_type(Message value);

} // ReqPort
