/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.app;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.riaps.app.TimeUnit#isMonths <em>Months</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.TimeUnit#isDays <em>Days</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.TimeUnit#isSeconds <em>Seconds</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.TimeUnit#isMilliseconds <em>Milliseconds</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.TimeUnit#isNanoseconds <em>Nanoseconds</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.TimeUnit#isMicroseconds <em>Microseconds</em>}</li>
 * </ul>
 *
 * @see edu.vanderbilt.riaps.app.AppPackage#getTimeUnit()
 * @model
 * @generated
 */
public interface TimeUnit extends EObject
{
  /**
   * Returns the value of the '<em><b>Months</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Months</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Months</em>' attribute.
   * @see #setMonths(boolean)
   * @see edu.vanderbilt.riaps.app.AppPackage#getTimeUnit_Months()
   * @model
   * @generated
   */
  boolean isMonths();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.TimeUnit#isMonths <em>Months</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Months</em>' attribute.
   * @see #isMonths()
   * @generated
   */
  void setMonths(boolean value);

  /**
   * Returns the value of the '<em><b>Days</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Days</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Days</em>' attribute.
   * @see #setDays(boolean)
   * @see edu.vanderbilt.riaps.app.AppPackage#getTimeUnit_Days()
   * @model
   * @generated
   */
  boolean isDays();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.TimeUnit#isDays <em>Days</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Days</em>' attribute.
   * @see #isDays()
   * @generated
   */
  void setDays(boolean value);

  /**
   * Returns the value of the '<em><b>Seconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Seconds</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seconds</em>' attribute.
   * @see #setSeconds(boolean)
   * @see edu.vanderbilt.riaps.app.AppPackage#getTimeUnit_Seconds()
   * @model
   * @generated
   */
  boolean isSeconds();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.TimeUnit#isSeconds <em>Seconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seconds</em>' attribute.
   * @see #isSeconds()
   * @generated
   */
  void setSeconds(boolean value);

  /**
   * Returns the value of the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Milliseconds</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Milliseconds</em>' attribute.
   * @see #setMilliseconds(boolean)
   * @see edu.vanderbilt.riaps.app.AppPackage#getTimeUnit_Milliseconds()
   * @model
   * @generated
   */
  boolean isMilliseconds();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.TimeUnit#isMilliseconds <em>Milliseconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Milliseconds</em>' attribute.
   * @see #isMilliseconds()
   * @generated
   */
  void setMilliseconds(boolean value);

  /**
   * Returns the value of the '<em><b>Nanoseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nanoseconds</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nanoseconds</em>' attribute.
   * @see #setNanoseconds(boolean)
   * @see edu.vanderbilt.riaps.app.AppPackage#getTimeUnit_Nanoseconds()
   * @model
   * @generated
   */
  boolean isNanoseconds();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.TimeUnit#isNanoseconds <em>Nanoseconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nanoseconds</em>' attribute.
   * @see #isNanoseconds()
   * @generated
   */
  void setNanoseconds(boolean value);

  /**
   * Returns the value of the '<em><b>Microseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Microseconds</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Microseconds</em>' attribute.
   * @see #setMicroseconds(boolean)
   * @see edu.vanderbilt.riaps.app.AppPackage#getTimeUnit_Microseconds()
   * @model
   * @generated
   */
  boolean isMicroseconds();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.app.TimeUnit#isMicroseconds <em>Microseconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Microseconds</em>' attribute.
   * @see #isMicroseconds()
   * @generated
   */
  void setMicroseconds(boolean value);

} // TimeUnit
