/*
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.ide.contentassist.antlr;

import com.google.inject.Inject;
import edu.vanderbilt.riaps.ide.contentassist.antlr.internal.InternalDatatypesParser;
import edu.vanderbilt.riaps.services.DatatypesGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class DatatypesParser extends AbstractContentAssistParser {

	@Inject
	private DatatypesGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDatatypesParser createParser() {
		InternalDatatypesParser result = new InternalDatatypesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getFTypeRefAccess().getAlternatives(), "rule__FTypeRef__Alternatives");
					put(grammarAccess.getFTypeAccess().getAlternatives(), "rule__FType__Alternatives");
					put(grammarAccess.getFBasicTypeIdAccess().getAlternatives(), "rule__FBasicTypeId__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getImportedFQNAccess().getGroup(), "rule__ImportedFQN__Group__0");
					put(grammarAccess.getImportedFQNAccess().getGroup_1(), "rule__ImportedFQN__Group_1__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getFTypeCollectionAccess().getGroup(), "rule__FTypeCollection__Group__0");
					put(grammarAccess.getFTypeCollectionAccess().getGroup_4(), "rule__FTypeCollection__Group_4__0");
					put(grammarAccess.getFMessageAccess().getGroup(), "rule__FMessage__Group__0");
					put(grammarAccess.getFMessageAccess().getGroup_3(), "rule__FMessage__Group_3__0");
					put(grammarAccess.getFVersionAccess().getGroup(), "rule__FVersion__Group__0");
					put(grammarAccess.getFStructTypeAccess().getGroup(), "rule__FStructType__Group__0");
					put(grammarAccess.getFStructTypeAccess().getGroup_3(), "rule__FStructType__Group_3__0");
					put(grammarAccess.getFEnumerationTypeAccess().getGroup(), "rule__FEnumerationType__Group__0");
					put(grammarAccess.getFEnumerationTypeAccess().getGroup_3(), "rule__FEnumerationType__Group_3__0");
					put(grammarAccess.getFEnumerationTypeAccess().getGroup_5(), "rule__FEnumerationType__Group_5__0");
					put(grammarAccess.getFEnumerationTypeAccess().getGroup_5_1(), "rule__FEnumerationType__Group_5_1__0");
					put(grammarAccess.getFEnumeratorAccess().getGroup(), "rule__FEnumerator__Group__0");
					put(grammarAccess.getFEnumeratorAccess().getGroup_2(), "rule__FEnumerator__Group_2__0");
					put(grammarAccess.getFMapTypeAccess().getGroup(), "rule__FMapType__Group__0");
					put(grammarAccess.getFFieldAccess().getGroup(), "rule__FField__Group__0");
					put(grammarAccess.getFFieldAccess().getGroup_1(), "rule__FField__Group_1__0");
					put(grammarAccess.getModelAccess().getNameAssignment_2(), "rule__Model__NameAssignment_2");
					put(grammarAccess.getModelAccess().getImportsAssignment_3(), "rule__Model__ImportsAssignment_3");
					put(grammarAccess.getModelAccess().getTypeCollectionsAssignment_4(), "rule__Model__TypeCollectionsAssignment_4");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getFTypeCollectionAccess().getNameAssignment_2(), "rule__FTypeCollection__NameAssignment_2");
					put(grammarAccess.getFTypeCollectionAccess().getVersionAssignment_4_1(), "rule__FTypeCollection__VersionAssignment_4_1");
					put(grammarAccess.getFTypeCollectionAccess().getTypesAssignment_5(), "rule__FTypeCollection__TypesAssignment_5");
					put(grammarAccess.getFMessageAccess().getDerivedAssignment_1(), "rule__FMessage__DerivedAssignment_1");
					put(grammarAccess.getFMessageAccess().getNameAssignment_2(), "rule__FMessage__NameAssignment_2");
					put(grammarAccess.getFMessageAccess().getKeyAssignment_3_1(), "rule__FMessage__KeyAssignment_3_1");
					put(grammarAccess.getFVersionAccess().getMajorAssignment_3(), "rule__FVersion__MajorAssignment_3");
					put(grammarAccess.getFVersionAccess().getMinorAssignment_5(), "rule__FVersion__MinorAssignment_5");
					put(grammarAccess.getFTypeRefAccess().getPredefinedAssignment_0(), "rule__FTypeRef__PredefinedAssignment_0");
					put(grammarAccess.getFTypeRefAccess().getDerivedAssignment_1(), "rule__FTypeRef__DerivedAssignment_1");
					put(grammarAccess.getFStructTypeAccess().getNameAssignment_2(), "rule__FStructType__NameAssignment_2");
					put(grammarAccess.getFStructTypeAccess().getBaseAssignment_3_1(), "rule__FStructType__BaseAssignment_3_1");
					put(grammarAccess.getFStructTypeAccess().getElementsAssignment_5(), "rule__FStructType__ElementsAssignment_5");
					put(grammarAccess.getFEnumerationTypeAccess().getNameAssignment_2(), "rule__FEnumerationType__NameAssignment_2");
					put(grammarAccess.getFEnumerationTypeAccess().getBaseAssignment_3_1(), "rule__FEnumerationType__BaseAssignment_3_1");
					put(grammarAccess.getFEnumerationTypeAccess().getEnumeratorsAssignment_5_0(), "rule__FEnumerationType__EnumeratorsAssignment_5_0");
					put(grammarAccess.getFEnumerationTypeAccess().getEnumeratorsAssignment_5_1_1(), "rule__FEnumerationType__EnumeratorsAssignment_5_1_1");
					put(grammarAccess.getFEnumeratorAccess().getNameAssignment_1(), "rule__FEnumerator__NameAssignment_1");
					put(grammarAccess.getFEnumeratorAccess().getValueAssignment_2_1(), "rule__FEnumerator__ValueAssignment_2_1");
					put(grammarAccess.getFMapTypeAccess().getNameAssignment_2(), "rule__FMapType__NameAssignment_2");
					put(grammarAccess.getFMapTypeAccess().getKeyTypeAssignment_4(), "rule__FMapType__KeyTypeAssignment_4");
					put(grammarAccess.getFMapTypeAccess().getValueTypeAssignment_6(), "rule__FMapType__ValueTypeAssignment_6");
					put(grammarAccess.getFFieldAccess().getTypeAssignment_0(), "rule__FField__TypeAssignment_0");
					put(grammarAccess.getFFieldAccess().getListAssignment_1_0(), "rule__FField__ListAssignment_1_0");
					put(grammarAccess.getFFieldAccess().getNameAssignment_2(), "rule__FField__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalDatatypesParser typedParser = (InternalDatatypesParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DatatypesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DatatypesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
