/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.generator;

import com.google.inject.Inject;
import edu.vanderbilt.riaps.generator.CapnProtoGenerator;
import edu.vanderbilt.riaps.generator.IDLGenerator;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class DatatypesGenerator extends AbstractGenerator {
  @Inject
  private IDLGenerator g2;
  
  @Inject
  private CapnProtoGenerator g1;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    this.g2.doGenerate(resource, fsa, context);
    this.g1.doGenerate(resource, fsa, context);
  }
}
