/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.app.impl;

import edu.vanderbilt.riaps.app.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AppFactoryImpl extends EFactoryImpl implements AppFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static AppFactory init()
  {
    try
    {
      AppFactory theAppFactory = (AppFactory)EPackage.Registry.INSTANCE.getEFactory(AppPackage.eNS_URI);
      if (theAppFactory != null)
      {
        return theAppFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new AppFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AppFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case AppPackage.MDODEL: return createMdodel();
      case AppPackage.FORMAL_DEFAULT: return createFormalDefault();
      case AppPackage.STRING_DEFAULT: return createStringDefault();
      case AppPackage.NUMBER_DEFAULT: return createNumberDefault();
      case AppPackage.BOOL_DEFAULT: return createBoolDefault();
      case AppPackage.COLLECTION: return createCollection();
      case AppPackage.COMPONENT_COLLECTION: return createComponentCollection();
      case AppPackage.APPLICATION: return createApplication();
      case AppPackage.DEPLOYMENT_CONSTRAINT: return createDeploymentConstraint();
      case AppPackage.COLLOCATE_CONSTRAINT: return createCollocateConstraint();
      case AppPackage.DISTRIBUTE_CONSTRAINT: return createDistributeConstraint();
      case AppPackage.IMPORT: return createImport();
      case AppPackage.MESSAGE_COLLECTION: return createMessageCollection();
      case AppPackage.MESSAGE: return createMessage();
      case AppPackage.ARTIFACT: return createArtifact();
      case AppPackage.COMPONENT: return createComponent();
      case AppPackage.DEVICE_COMPONENT: return createDeviceComponent();
      case AppPackage.APP_COMPONENT: return createAppComponent();
      case AppPackage.MEMORY_UNITS: return createMemoryUnits();
      case AppPackage.REQUIREMENT: return createRequirement();
      case AppPackage.PORT: return createPort();
      case AppPackage.RATE_LIMIT: return createRateLimit();
      case AppPackage.PUB_PORT: return createPubPort();
      case AppPackage.SUB_PORT: return createSubPort();
      case AppPackage.DEADLINE: return createDeadline();
      case AppPackage.CLNT_PORT: return createClntPort();
      case AppPackage.SRV_PORT: return createSrvPort();
      case AppPackage.REQ_PORT: return createReqPort();
      case AppPackage.TIME_UNIT: return createTimeUnit();
      case AppPackage.TIM_PORT: return createTimPort();
      case AppPackage.INS_PORT: return createInsPort();
      case AppPackage.COMPONENT_FORMAL: return createComponentFormal();
      case AppPackage.ACTOR_FORMAL: return createActorFormal();
      case AppPackage.ACTOR: return createActor();
      case AppPackage.INSTANCE_SECTION: return createInstanceSection();
      case AppPackage.WIRE: return createWire();
      case AppPackage.ACTUAL: return createActual();
      case AppPackage.ACTUAL_VALUE: return createActualValue();
      case AppPackage.INSTANCE: return createInstance();
      case AppPackage.MODEL: return createModel();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Mdodel createMdodel()
  {
    MdodelImpl mdodel = new MdodelImpl();
    return mdodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FormalDefault createFormalDefault()
  {
    FormalDefaultImpl formalDefault = new FormalDefaultImpl();
    return formalDefault;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StringDefault createStringDefault()
  {
    StringDefaultImpl stringDefault = new StringDefaultImpl();
    return stringDefault;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NumberDefault createNumberDefault()
  {
    NumberDefaultImpl numberDefault = new NumberDefaultImpl();
    return numberDefault;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BoolDefault createBoolDefault()
  {
    BoolDefaultImpl boolDefault = new BoolDefaultImpl();
    return boolDefault;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Collection createCollection()
  {
    CollectionImpl collection = new CollectionImpl();
    return collection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentCollection createComponentCollection()
  {
    ComponentCollectionImpl componentCollection = new ComponentCollectionImpl();
    return componentCollection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Application createApplication()
  {
    ApplicationImpl application = new ApplicationImpl();
    return application;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DeploymentConstraint createDeploymentConstraint()
  {
    DeploymentConstraintImpl deploymentConstraint = new DeploymentConstraintImpl();
    return deploymentConstraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CollocateConstraint createCollocateConstraint()
  {
    CollocateConstraintImpl collocateConstraint = new CollocateConstraintImpl();
    return collocateConstraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DistributeConstraint createDistributeConstraint()
  {
    DistributeConstraintImpl distributeConstraint = new DistributeConstraintImpl();
    return distributeConstraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MessageCollection createMessageCollection()
  {
    MessageCollectionImpl messageCollection = new MessageCollectionImpl();
    return messageCollection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Message createMessage()
  {
    MessageImpl message = new MessageImpl();
    return message;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Artifact createArtifact()
  {
    ArtifactImpl artifact = new ArtifactImpl();
    return artifact;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Component createComponent()
  {
    ComponentImpl component = new ComponentImpl();
    return component;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DeviceComponent createDeviceComponent()
  {
    DeviceComponentImpl deviceComponent = new DeviceComponentImpl();
    return deviceComponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AppComponent createAppComponent()
  {
    AppComponentImpl appComponent = new AppComponentImpl();
    return appComponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MemoryUnits createMemoryUnits()
  {
    MemoryUnitsImpl memoryUnits = new MemoryUnitsImpl();
    return memoryUnits;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Requirement createRequirement()
  {
    RequirementImpl requirement = new RequirementImpl();
    return requirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Port createPort()
  {
    PortImpl port = new PortImpl();
    return port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RateLimit createRateLimit()
  {
    RateLimitImpl rateLimit = new RateLimitImpl();
    return rateLimit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PubPort createPubPort()
  {
    PubPortImpl pubPort = new PubPortImpl();
    return pubPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SubPort createSubPort()
  {
    SubPortImpl subPort = new SubPortImpl();
    return subPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Deadline createDeadline()
  {
    DeadlineImpl deadline = new DeadlineImpl();
    return deadline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClntPort createClntPort()
  {
    ClntPortImpl clntPort = new ClntPortImpl();
    return clntPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SrvPort createSrvPort()
  {
    SrvPortImpl srvPort = new SrvPortImpl();
    return srvPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReqPort createReqPort()
  {
    ReqPortImpl reqPort = new ReqPortImpl();
    return reqPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TimeUnit createTimeUnit()
  {
    TimeUnitImpl timeUnit = new TimeUnitImpl();
    return timeUnit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TimPort createTimPort()
  {
    TimPortImpl timPort = new TimPortImpl();
    return timPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InsPort createInsPort()
  {
    InsPortImpl insPort = new InsPortImpl();
    return insPort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentFormal createComponentFormal()
  {
    ComponentFormalImpl componentFormal = new ComponentFormalImpl();
    return componentFormal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ActorFormal createActorFormal()
  {
    ActorFormalImpl actorFormal = new ActorFormalImpl();
    return actorFormal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Actor createActor()
  {
    ActorImpl actor = new ActorImpl();
    return actor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InstanceSection createInstanceSection()
  {
    InstanceSectionImpl instanceSection = new InstanceSectionImpl();
    return instanceSection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Wire createWire()
  {
    WireImpl wire = new WireImpl();
    return wire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Actual createActual()
  {
    ActualImpl actual = new ActualImpl();
    return actual;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ActualValue createActualValue()
  {
    ActualValueImpl actualValue = new ActualValueImpl();
    return actualValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Instance createInstance()
  {
    InstanceImpl instance = new InstanceImpl();
    return instance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AppPackage getAppPackage()
  {
    return (AppPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static AppPackage getPackage()
  {
    return AppPackage.eINSTANCE;
  }

} //AppFactoryImpl
