/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.app.impl;

import edu.vanderbilt.riaps.app.AppPackage;
import edu.vanderbilt.riaps.app.Artifact;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Artifact</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.riaps.app.impl.ArtifactImpl#isJar <em>Jar</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.impl.ArtifactImpl#isSharedObject <em>Shared Object</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.impl.ArtifactImpl#isConfigurationFile <em>Configuration File</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.impl.ArtifactImpl#getName <em>Name</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.app.impl.ArtifactImpl#getPath <em>Path</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ArtifactImpl extends MinimalEObjectImpl.Container implements Artifact
{
  /**
   * The default value of the '{@link #isJar() <em>Jar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isJar()
   * @generated
   * @ordered
   */
  protected static final boolean JAR_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isJar() <em>Jar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isJar()
   * @generated
   * @ordered
   */
  protected boolean jar = JAR_EDEFAULT;

  /**
   * The default value of the '{@link #isSharedObject() <em>Shared Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSharedObject()
   * @generated
   * @ordered
   */
  protected static final boolean SHARED_OBJECT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSharedObject() <em>Shared Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSharedObject()
   * @generated
   * @ordered
   */
  protected boolean sharedObject = SHARED_OBJECT_EDEFAULT;

  /**
   * The default value of the '{@link #isConfigurationFile() <em>Configuration File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isConfigurationFile()
   * @generated
   * @ordered
   */
  protected static final boolean CONFIGURATION_FILE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isConfigurationFile() <em>Configuration File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isConfigurationFile()
   * @generated
   * @ordered
   */
  protected boolean configurationFile = CONFIGURATION_FILE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPath() <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected static final String PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPath() <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected String path = PATH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ArtifactImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AppPackage.Literals.ARTIFACT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isJar()
  {
    return jar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setJar(boolean newJar)
  {
    boolean oldJar = jar;
    jar = newJar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPackage.ARTIFACT__JAR, oldJar, jar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isSharedObject()
  {
    return sharedObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSharedObject(boolean newSharedObject)
  {
    boolean oldSharedObject = sharedObject;
    sharedObject = newSharedObject;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPackage.ARTIFACT__SHARED_OBJECT, oldSharedObject, sharedObject));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isConfigurationFile()
  {
    return configurationFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConfigurationFile(boolean newConfigurationFile)
  {
    boolean oldConfigurationFile = configurationFile;
    configurationFile = newConfigurationFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPackage.ARTIFACT__CONFIGURATION_FILE, oldConfigurationFile, configurationFile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPackage.ARTIFACT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPath()
  {
    return path;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPath(String newPath)
  {
    String oldPath = path;
    path = newPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AppPackage.ARTIFACT__PATH, oldPath, path));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AppPackage.ARTIFACT__JAR:
        return isJar();
      case AppPackage.ARTIFACT__SHARED_OBJECT:
        return isSharedObject();
      case AppPackage.ARTIFACT__CONFIGURATION_FILE:
        return isConfigurationFile();
      case AppPackage.ARTIFACT__NAME:
        return getName();
      case AppPackage.ARTIFACT__PATH:
        return getPath();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AppPackage.ARTIFACT__JAR:
        setJar((Boolean)newValue);
        return;
      case AppPackage.ARTIFACT__SHARED_OBJECT:
        setSharedObject((Boolean)newValue);
        return;
      case AppPackage.ARTIFACT__CONFIGURATION_FILE:
        setConfigurationFile((Boolean)newValue);
        return;
      case AppPackage.ARTIFACT__NAME:
        setName((String)newValue);
        return;
      case AppPackage.ARTIFACT__PATH:
        setPath((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AppPackage.ARTIFACT__JAR:
        setJar(JAR_EDEFAULT);
        return;
      case AppPackage.ARTIFACT__SHARED_OBJECT:
        setSharedObject(SHARED_OBJECT_EDEFAULT);
        return;
      case AppPackage.ARTIFACT__CONFIGURATION_FILE:
        setConfigurationFile(CONFIGURATION_FILE_EDEFAULT);
        return;
      case AppPackage.ARTIFACT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AppPackage.ARTIFACT__PATH:
        setPath(PATH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AppPackage.ARTIFACT__JAR:
        return jar != JAR_EDEFAULT;
      case AppPackage.ARTIFACT__SHARED_OBJECT:
        return sharedObject != SHARED_OBJECT_EDEFAULT;
      case AppPackage.ARTIFACT__CONFIGURATION_FILE:
        return configurationFile != CONFIGURATION_FILE_EDEFAULT;
      case AppPackage.ARTIFACT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AppPackage.ARTIFACT__PATH:
        return PATH_EDEFAULT == null ? path != null : !PATH_EDEFAULT.equals(path);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (jar: ");
    result.append(jar);
    result.append(", sharedObject: ");
    result.append(sharedObject);
    result.append(", configurationFile: ");
    result.append(configurationFile);
    result.append(", name: ");
    result.append(name);
    result.append(", path: ");
    result.append(path);
    result.append(')');
    return result.toString();
  }

} //ArtifactImpl
