/*
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAppScopeProvider extends DelegatingScopeProvider {
}
