/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.datatypes;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FEnumeration Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.vanderbilt.riaps.datatypes.FEnumerationType#getBase <em>Base</em>}</li>
 *   <li>{@link edu.vanderbilt.riaps.datatypes.FEnumerationType#getEnumerators <em>Enumerators</em>}</li>
 * </ul>
 *
 * @see edu.vanderbilt.riaps.datatypes.DatatypesPackage#getFEnumerationType()
 * @model
 * @generated
 */
public interface FEnumerationType extends FType
{
  /**
   * Returns the value of the '<em><b>Base</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Base</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' reference.
   * @see #setBase(FEnumerationType)
   * @see edu.vanderbilt.riaps.datatypes.DatatypesPackage#getFEnumerationType_Base()
   * @model
   * @generated
   */
  FEnumerationType getBase();

  /**
   * Sets the value of the '{@link edu.vanderbilt.riaps.datatypes.FEnumerationType#getBase <em>Base</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' reference.
   * @see #getBase()
   * @generated
   */
  void setBase(FEnumerationType value);

  /**
   * Returns the value of the '<em><b>Enumerators</b></em>' containment reference list.
   * The list contents are of type {@link edu.vanderbilt.riaps.datatypes.FEnumerator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enumerators</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumerators</em>' containment reference list.
   * @see edu.vanderbilt.riaps.datatypes.DatatypesPackage#getFEnumerationType_Enumerators()
   * @model containment="true"
   * @generated
   */
  EList<FEnumerator> getEnumerators();

} // FEnumerationType
